# Generated by Django 4.1 on 2022-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250, verbose_name='Your Number ')),
                ('sender', models.CharField(max_length=250, verbose_name='Your Name')),
                ('compliment', models.CharField(max_length=250, verbose_name='Your Compliment')),
                ('ctime', models.DateField()),
            ],
            options={
                'db_table': 'Compliment',
            },
        ),
    ]
